cctutorial/cctutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

cctutorial/polls/urls.py
from django.urls import path, re_path
from . import views


# polls/choices/
app_name = 'polls'
polls_url_base = 'polls/'

urlpatterns = [
    # ex: /
    path('', views.home, name='home'),
    # ex: /polls
    path(polls_url_base, views.index, name='index'),
    # ex: /polls/most-popular-choice/
    path(polls_url_base + 'most-popular-choice/', views.most_popular_choice, name='most-popular-choice'),
    # ex: /polls/choices/0010/
    re_path(polls_url_base + 'choices/(?P<pk>[0-9]{4})/', views.choices, name='choices'),  # 'choices/(?P<pk>[0-9]{1,4})/'
    # ex: /polls/choices/
    path(polls_url_base + 'choices/', views.choices, name='choices'),
    # ex: /polls/question/2023-09-16/ or /polls/question/2023/09/16/
    re_path(polls_url_base + 'question/(?P<pub_date>[0-9]{4}[-/][0-9]{2}[-/][0-9]{2})/', views.question, name='question'),
    # ex: /polls/question/
    path(polls_url_base + 'question/', views.question, name='question'),

    # from the tutorial
    # ex: /polls/5
    path(polls_url_base + '<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path(polls_url_base + '<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path(polls_url_base + '<int:question_id>/vote/', views.vote, name='vote'),
]

cctutorial/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    objects = models.Manager()


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    objects = models.Manager()

cctutorial/polls/views.py
from datetime import datetime, timedelta
from collections import defaultdict
from .models import Choice, Question
from django.db.models import F, Max

# from django.db.models.functions import Coalesce
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.urls import reverse
from django.contrib import messages


def home(request):
    return render(request, "home.html")  # add reverse() URL for home


# polls
def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    response = HttpResponse()
    response.delete_cookie("voted_date")
    return render(request, "polls/index.html", context)


def most_popular_choice(request):
    """
    After you have created a series of questions and choices,
    return the choice with the most votes of all choices. If there
    are multiples with the same number of votes, return al. For
    the choice, display the choice_text, number of votes and
    related Question id in the response below.
    """
    # max_votes = Choice.objects.aggregate(max_votes=Coalesce(Max('votes'), 0))['max_votes']
    max_votes = Choice.objects.aggregate(max_votes=Max("votes"))["max_votes"]
    popular_choices = Choice.objects.filter(votes=max_votes).values(
        "choice_text", "votes", "question"
    )
    # add exception and when no value is found
    context = {"popular_choices": popular_choices}
    return render(request, "polls/popular.html", context)


def choices(request, pk=None):
    """
    If a primary key is passed in, return only that choice object.
    If no primary key is passed in, return all choices ordered by the highest number of votes first.

    Show the related question in both instances.
    """
    if pk:
        try:
            selected_choice = Choice.objects.get(pk=int(pk))
            # selected_choice = get_object_or_404(Choice, pk=int(pk))
            related_question = selected_choice.question
            related_choices = Choice.objects.filter(question=related_question).order_by("-votes")
            context = {"choices": related_choices, "question": related_question}
            return render(request, "polls/choices.html", context)
        except Choice.DoesNotExist:
            messages.add_message(request, messages.ERROR, "Choice does not exist.")
            return render(
                request,
                "polls/choices.html",
                status=404)

    else:
        all_choices = (
            Choice.objects.all()
            .values("choice_text", "votes", question_text=F("question__question_text"))
            .order_by("-votes")
        )
        questions = defaultdict(list)
        for i in all_choices:
            question_t = i["question_text"]
            choices_t = {"choice_text": i["choice_text"], "votes": i["votes"]}
            questions[question_t].append(choices_t)
        context = {"questions": dict(questions)}
        return render(request, "polls/choices.html", context)


def question(request, pub_date=None):
    """
    If a primary key is passed in, return only that choice object.
    If no primary key is passed in, return all choices ordered by highest number of votes first.

    Show the related question in both instances
    """

    if pub_date:
        pub_date = pub_date.replace("/", "-")
        year, month, day = map(int, pub_date.split("-"))
        pub_date_converted = timezone.datetime(year, month, day)
        questions = Question.objects.filter(pub_date__date=pub_date_converted)
    else:
        pub_date = timezone.now().date()
        questions = Question.objects.filter(pub_date__date=pub_date)
    context = {"questions": questions}
    return render(request, "polls/questions.html", context)


# tutorial
def detail(request, question_id):
    """
    Not used. This is from the tutorial.
    """
    return HttpResponse("You're looking at question %s." % question_id)


def results(request, question_id):
    """
    Not used. This is from the tutorial.
    """
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question_pk = get_object_or_404(Question, pk=question_id)
    cookie_name = f"voted_question_{question_id}"
    cookie = request.COOKIES.get(cookie_name, False)
    try:
        selected_choice = question_pk.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        if _validate_cookie_for_voting(cookie):
            return render(
                request,
                "polls/detail.html",
                {
                    "question": question_pk,
                    "error_message": "Please select a choice.",
                },
            )
        return render(
            request,
            "polls/detail.html",
            {
                "question": question_pk,
                "error_message": "You have already voted for this question. Please vote for another question.",
            },
        )
    else:  # POST request
        if _validate_cookie_for_voting(cookie):
            selected_choice.votes += 1
            selected_choice.save()
            response = HttpResponseRedirect(
                reverse("polls:results", args=(question_id,))
            )
            response.set_cookie(
                cookie_name, timezone.now().strftime("%a, %d-%b-%Y %H:%M:%S GMT")
            )
            return response
        return render(
            request,
            "polls/detail.html",
            {
                "question": question_pk,
                "error_message": "You have already voted for this question. Please vote for another question.",
            },
        )


def _validate_cookie_for_voting(cookie: str):
    """
    return True if cookie expired, more than 24 hours, the user can vote
    return False if cookie is valid, less than 24 hours, the user can't vote
    """
    try:
        cookie_datetime = datetime.strptime(cookie, '%a, %d-%b-%Y %H:%M:%S GMT')  # change to timezone
        cookie_datetime = timezone.make_aware(cookie_datetime, timezone.utc)
        time_difference = timezone.now() - cookie_datetime
        one_day = timedelta(days=1)
        if time_difference > one_day:
            return True
        return False
    except (ValueError, TypeError):
        return True

cctutorial/cctutorial/templates/base.html
{% comment %} {% load static %} {% endcomment %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% comment %} <img src="{% static 'images/sitelogo.png' %}" alt="Logo"> {% endcomment %}
    {% block content %}{% endblock %}
</body>
</html>

cctutorial/polls/templates/choices.html
{% extends "base.html" %} {% block title %}Choices{% endblock %} {% block
content %}

<h2>Polls</h2>

{% if question %}
<p>Question: {{ question.question_text }}</p>
<ul>
  {% for choice in choices %}
  <li>Choice: {{ choice.choice_text }} - Votes: {{ choice.votes }}</li>
  {% endfor %}
</ul>
{% else %}
<ul>
  {% for question, choices in questions.items %}
  <li>
    <p>Question: {{ question }}</p>
    <ul>
      {% if choices %} {% for choice in choices %}
      <li>Choice: {{ choice.choice_text }} - Votes: {{ choice.votes }}</li>
      {% endfor %} {% else %}
      <li>No choices available.</li>
      {% endif %}
    </ul>
  </li>
  {% endfor %}
</ul>

{% endif %} {% endblock %}

cctutorial/polls/templates/home.html
{% extends "base.html" %} {% block title %}Homepage{% endblock %}
{% block content %}

<h1>Welcome to the Homepage</h1>

<p>
  <a href="{% url 'admin:index' %}">Admin Homepage</a><br />
  <a href="{% url 'polls:index' %}">Polls Section</a>
</p>

{% endblock %}

cctutorial/polls/templates/polls/choices.html
{% extends "base.html" %} {% block title %}Choices{% endblock %}
{% block content %}

<h2>Polls</h2>

{% if messages %}
{% for message in messages %}
<h3>{{ message }}</h3>
{% endfor %}
{% endif %}


{% if question %}
<p>Question: {{ question.question_text }}</p>
<ul>
  {% for choice in choices %}
  <li>Choice: {{ choice.choice_text }} - Votes: {{ choice.votes }}</li>
  {% endfor %}
</ul>

{% elif questions %}

<ul>
  {% for question, choices in questions.items %}
  <li>
    <p>Question: {{ question }}</p>
    <ul>
      {% if choices %} {% for choice in choices %}
      <li>Choice: {{ choice.choice_text }} - Votes: {{ choice.votes }}</li>
      {% endfor %} {% else %}
      <li>No choices available.</li>
      {% endif %}
    </ul>
  </li>
  {% endfor %}
</ul>

{% else %}

<p>{{ error_message }}</p>

{% endif %}



{% endblock %}

cctutorial/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %} 
    {% for choice in question.choice_set.all %}
        <input
        type="radio"
        name="choice"
        id="choice{{ forloop.counter }}"
        value="{{ choice.id }}"
        />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
        ><br />
    {% endfor %}
    </fieldset>
    <input type="submit" value="Vote" />
</form>

cctutorial/polls/templates/polls/index.html
{% extends "base.html" %} {% block title %}Index{% endblock %}

{% block content %}

<h2>All Questions</h2>


{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li>
    <b>Question:</b>
    <a href="{% url 'admin:polls_question_change' object_id=question.id %}">{{ question.question_text }}</a>
     - <b>Publication date:</b> 
    {{ question.pub_date }}. <a href="{% url 'polls:vote' question_id=question.id %}">Vote [user view]</a>
  </li>  
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}


<h2>Other links</h2>

<ul>
  <li>
    <b>Top 5 most popular </b><a href="{% url 'polls:most-popular-choice' %}">Link</a>
  </li>
  <li>
    <b>All choices </b><a href="{% url 'polls:choices' %}">Link</a>
  </li>
  <li>
    <b>Today's question </b><a href="{% url 'polls:question' %}">Link</a>
  </li>
</ul>



{% endblock %}

cctutorial/polls/templates/polls/popular.html
{% extends "base.html" %} {% block title %}Popular{% endblock %}

{% block content %}

<h2>Most Popular Choice</h2>
{% for popular in popular_choices %}
<p>Question id: {{ popular.question }}</p>
<ul>
  <li>Choice: {{ popular.choice_text }} - Votes: {{ popular.votes }}</li>
</ul>
{% endfor %} {% endblock %}

cctutorial/polls/templates/polls/questions.html
{% extends "base.html" %} {% block title %}Questions{% endblock %}

{% block content %}

<h2>Questions</h2>
{% if questions %}
  {% for question in questions %}
  <ul>
    <li>
      <b>Question:</b> {{ question.question_text }} - <b>Publication date:</b>
      {{ question.pub_date }}
    </li>
  </ul>
  {% endfor %}
{% else %}
  <p>No questions found.</p>
{% endif %}

{% endblock %}

cctutorial/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:index' %}">Go to all questions</a>

cctutorial/polls/templates/popular.html
{% extends "base.html" %} {% block title %}Popular{% endblock %} {% block
content %}

<h2>Most Popular</h2>
{% for popular in popular_choices %}
<p>Question id: {{ popular.question }}</p>
<ul>
  <li>Choice: {{ popular.choice_text }} - Votes: {{ popular.votes }}</li>
</ul>
{% endfor %} {% endblock %}